export const GET_ALL_TODO_REQUEST = "GET_ALL_TODO_REQUEST"
export const GET_ALL_TODO_SUCCESS = "GET_ALL_TODO_SUCCESS"
export const GET_ALL_TODO_FAIL = "GET_ALL_TODO_FAIL"


export const CREATE_TODO_REQUEST   = "CREATE_TODO_REQUEST"
export const CREATE_TODO_SUCCESS   = "CREATE_TODO_SUCCESS"
export const CREATE_TODO_FAIL   = "CREATE_TODO_FAIL"


export const UPDATE_TODO_REQUEST  = "UPDATE_TODO_REQUEST"
export const UPDATE_TODO_SUCCESS  = "UPDATE_TODO_SUCCESS"
export const UPDATE_TODO_FAIL   = "UPDATE_TODO_FAIL "


export const DELETE_TODO_REQUEST  = "DELETE_TODO_REQUEST"
export const DELETE_TODO_SUCCESS  = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAIL  = "DELETE_TODO_FAIL"

export const CATCH_ERROR  = "CATCH_ERROR"